### ISSUE TITLE
Issue when starting covalent programmatically

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#1481]
### Environment

- **Covalent version**: `0.212.1rc0` although it can be traced back to `0.202.0.post1`
- **Python version**: 3.9.15
- **Operating system**: Ubuntu 20.04

### What is happening?

When covalent is run programmatically, even though it says the covalent server has started, the dask cluster takes some time to get set up. Which leads to adding a sleep statement right after doing `covalent start`. This is not an issue if someone does `covalent start` on their terminal and then runs their workflow manually because that small amount of time gap is sufficient for dask to set its cluster up.

### How can we reproduce the issue?

```python
import os
import covalent as ct

os.system("covalent start")

@ct.lattice
@ct.electron
def task():
    return 42

result = ct.dispatch_sync(task)()
print(result)
os.system("covalent stop")
```

This will fail with the error (you might have to check the logs):
```python
Node generate_normal_time_series_set failed: 
Traceback (most recent call last):
  File "/home/neptune/anaconda3/envs/QVR/lib/python3.9/site-packages/covalent_dispatcher/_core/execution.py", line 353, in _run_task
    output, stdout, stderr = await execute_callable()
  File "/home/neptune/anaconda3/envs/QVR/lib/python3.9/site-packages/covalent/executor/base.py", line 387, in execute
    result = await self.run(function, args, kwargs, task_metadata)
  File "/home/neptune/anaconda3/envs/QVR/lib/python3.9/site-packages/covalent/executor/executor_plugins/dask.py", line 108, in run
    await dask_client
  File "/home/neptune/anaconda3/envs/QVR/lib/python3.9/site-packages/distributed/client.py", line 1213, in _start
    await self._ensure_connected(timeout=timeout)
  File "/home/neptune/anaconda3/envs/QVR/lib/python3.9/site-packages/distributed/client.py", line 1276, in _ensure_connected
    comm = await connect(
  File "/home/neptune/anaconda3/envs/QVR/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/home/neptune/anaconda3/envs/QVR/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/home/neptune/anaconda3/envs/QVR/lib/python3.9/site-packages/distributed/comm/tcp.py", line 487, in connect
    ip, port = parse_host_port(address)
  File "/home/neptune/anaconda3/envs/QVR/lib/python3.9/site-packages/distributed/comm/addressing.py", line 95, in parse_host_port
    port = _default()
  File "/home/neptune/anaconda3/envs/QVR/lib/python3.9/site-packages/distributed/comm/addressing.py", line 73, in _default
    raise ValueError(f"missing port number in address {address!r}")
ValueError: missing port number in address ''
```

### What should happen?

`_graceful_start` should have a mechanism to check whether covalent and the dask cluster have started completely and only then exit and print the "Covalent server has started..." line. Ideally, no sleep statements should be present in this function.

**Comment by madhur-tandon** [comment]
I wasn't able to reproduce this, is it resolved?
CC: @santoshkumarradha

**Comment by santoshkumarradha** [comment]
I just checked, Seems like this issue is auto solved! thanks @madhur-tandon  !

Closing this.
