### ISSUE TITLE
Covalent commands stuck without any way to debug

### ISSUE THREAD

**Issue by pradeepmantha** [AgnostiqHQ/covalent#1895]
### Environment

- **Covalent version**:covalent-0.220.0.post2
- **Python version**: 3.8
- **Operating system**: SUSE Enterprise 15

### What is happening?

Any covalent command stucks
python
Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import covalent
covalent.__version__
^C^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/py38/lib/python3.8/site-packages/covalent/__init__.py", line 22, in <module>
    from . import executor, leptons  # nopycln: import
  File "py38/lib/python3.8/site-packages/covalent/executor/__init__.py", line 32, in <module>
    from .._shared_files import logger
  File "/py38/lib/python3.8/site-packages/covalent/_shared_files/logger.py", line 30, in <module>
    log_level = get_config("sdk.log_level").upper()
  File "/py38/lib/python3.8/site-packages/covalent/_shared_files/config.py", line 243, in get_config
    cm = ConfigManager()
  File "/py38/lib/python3.8/site-packages/covalent/_shared_files/config.py", line 51, in __init__
    self.update_config()
  File "py38/lib/python3.8/site-packages/covalent/_shared_files/config.py", line 113, in update_config
    fcntl.lockf(f, fcntl.LOCK_EX)

### How can we reproduce the issue?

Test on SUSE enterprise with latest version of covalent and py3.8

### What should happen?

covalent start will just stuck for long time

**Comment by Andrew-S-Rosen** [comment]
This suggests that the `COVALENT_CONFIG_DIR` is set to a location that does not support file locking. Duplicate of #1697.

**Comment by santoshkumarradha** [comment]
> This suggests that the `COVALENT_CONFIG_DIR` is set to a location that does not support file locking. See #1697.

Yes this does seem like config file smell. @kessler-frost can you add this in?

**Comment by Andrew-S-Rosen** [comment]
I will note that @pradeepmantha direct messaged me the following:

>  I was able to bring up covalent server on the perlmutter compute node successfully after changing the config directory.
