### ISSUE TITLE
setup.py webapp failing with yarn error

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#201]
### Environment

- **Covalent version**: `0.32.3`
- **Python version**: `3.8.12`
- **Operating system**: tried on both `macOS 12.3` and `Debian GNU/Linux 11 (bullseye)`

### What is happening?

When I try to `python setup.py webapp` it crashes with the following error
```
~/covalent (develop|…) $ python setup.py webapp                                                      (covalent-dev)
running webapp
Traceback (most recent call last):
  File "setup.py", line 161, in <module>
    setup(**setup_info)
  File "/opt/anaconda3/envs/covalent-dev/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "/opt/anaconda3/envs/covalent-dev/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/opt/anaconda3/envs/covalent-dev/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/opt/anaconda3/envs/covalent-dev/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/covalent-dev/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 104, in run
    subprocess.run(
  File "/opt/anaconda3/envs/covalent-dev/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['yarn', 'build']' returned non-zero exit status 1.
```

### How can we reproduce the issue?

Follow the steps in CONTRIBUTING, starting with
https://github.com/AgnostiqHQ/covalent/blob/develop/CONTRIBUTING.md?plain=1#L17

### What should happen?

The UI should be built successfully

**Comment by scottwn** [comment]
running `yarn build` directly in `webapp` provides more output
```
~/c/c/webapp (develop|…) $ yarn build                                                                (covalent-dev)
yarn run v1.22.17
warning ../../../package.json: No license field
$ react-scripts build
Creating an optimized production build...
/Users/scott/covalent/covalent_ui/webapp/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/scott/covalent/covalent_ui/webapp/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/scott/covalent/covalent_ui/webapp/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/scott/covalent/covalent_ui/webapp/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/scott/covalent/covalent_ui/webapp/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/scott/covalent/covalent_ui/webapp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/scott/covalent/covalent_ui/webapp/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/scott/covalent/covalent_ui/webapp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/scott/covalent/covalent_ui/webapp/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.4.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by scottwn** [comment]
the fix is https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

**Comment by m-chaturvedi** [comment]
BTW, perhaps this could be a bit fragile way of doing what you're asking in the stackoverflow?

`wget -q https://raw.githubusercontent.com/nodejs/node/$(node --version)/src/node_version.h -O - | grep NODE_VERSION_IS_LTS | cut -f3 -d' '`

https://github.com/nodejs/node/blob/8fe7979b7b740e67aa444172c555a86bf0e43aee/src/node_version.h#L29
