### ISSUE TITLE
`get_all_results` fails in the result service

### ISSUE THREAD

**Issue by kessler-frost** [AgnostiqHQ/covalent#335]
After starting all the services, the ui backend contacts the result service to get all the previous results, but that fails with the following error:

```
File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/refactor/results/app/api/api_v0/endpoints/workflow.py", line 215, in get_results
    responses = await asyncio.gather(*tasks, return_exceptions=False)
  File "/refactor/results/app/api/api_v0/endpoints/workflow.py", line 149, in _concurrent_download_and_serialize
    result = pickle.loads(result_binary)
_pickle.UnpicklingError: invalid load key, '{'.
```

since the query is done multiple times, the logs are filled with this. It also leads to the following error happening when a dispatch is made:

```
covalent_results           | ERROR:    Exception in ASGI application
covalent_results           | Traceback (most recent call last):
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
covalent_results           |     result = await app(self.scope, self.receive, self.send)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
covalent_results           |     return await self.app(scope, receive, send)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 259, in __call__
covalent_results           |     await super().__call__(scope, receive, send)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
covalent_results           |     await self.middleware_stack(scope, receive, send)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
covalent_results           |     raise exc
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
covalent_results           |     await self.app(scope, receive, _send)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 92, in __call__
covalent_results           |     await self.simple_response(scope, receive, send, request_headers=headers)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 147, in simple_response
covalent_results           |     await self.app(scope, receive, send)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
covalent_results           |     raise exc
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
covalent_results           |     await self.app(scope, receive, sender)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
covalent_results           |     raise e
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
covalent_results           |     await self.app(scope, receive, send)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
covalent_results           |     await route.handle(scope, receive, send)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
covalent_results           |     await self.app(scope, receive, send)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
covalent_results           |     response = await func(request)
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
covalent_results           |     raw_response = await run_endpoint_function(
covalent_results           |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
covalent_results           |     return await dependant.call(**values)
covalent_results           |   File "/refactor/results/app/api/api_v0/endpoints/workflow.py", line 215, in get_results
covalent_results           |     responses = await asyncio.gather(*tasks, return_exceptions=False)
covalent_results           |   File "/refactor/results/app/api/api_v0/endpoints/workflow.py", line 150, in _concurrent_download_and_serialize
covalent_results           |     result_json = json.loads(encode_result(result))
covalent_results           |   File "/covalent_dispatcher/_db/dispatchdb.py", line 114, in encode_result
covalent_results           |     "graph": extract_graph(result_obj.lattice.transport_graph._graph),
covalent_results           | AttributeError: 'bytes' object has no attribute '_graph'
```

**Comment by scottwn** [comment]
There is a related issue with unpickling results objects. What we have found is that when the pickle object is created in a local conda env and `POST`ed to the results service, the service breaks if the service env differs from the local env—which will happen in nearly all cases. That issue is tracked in #313 

In summary

#335 (this issue) tracks the fix for `GET` `/results`
#313 tracks the fix for `POST` `/result`

**Comment by scottwn** [comment]
confirmed fixed in https://github.com/AgnostiqHQ/covalent/pull/398
