### ISSUE TITLE
docker-compose failing

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#372]
### Environment

- **Covalent version**: 0.79.1
- **Python version**: 3.10.0
- **Operating system**: macOS 12.3.1

### What is happening?

`docker-compose build` is failing

```
~/covalent (develop|…) [255]$ docker-compose build
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 726, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[3728] Failed to execute script docker-compose
```

### How can we reproduce the issue?

run `docker-compose build`

### What should happen?

the service containers should get built

**Comment by scottwn** [comment]
this was user error on my part sorry

**Comment by scottwn** [comment]
The original error was just because I foolishly didn't have Docker running, but after starting Docker I have a different error
```
#8 23.80   Running setup.py develop for cova
#8 24.98     error: subprocess-exited-with-error
#8 24.98
#8 24.98     × python setup.py develop did not run successfully.
#8 24.98     │ exit code: 1
#8 24.98     ╰─> [6 lines of output]
#8 24.98         running develop
#8 24.98         /tmp/pip-build-env-ywijo3xu/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
#8 24.98           warnings.warn(
#8 24.98         /tmp/pip-build-env-ywijo3xu/overlay/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
#8 24.98           warnings.warn(
#8 24.98         error: [Errno 2] No such file or directory: 'unzip'
#8 24.98         [end of output]
#8 24.98
#8 24.98     note: This error originates from a subprocess, and is likely not a problem with pip.
#8 24.98 error: subprocess-exited-with-error
#8 24.98
#8 24.98 × python setup.py develop did not run successfully.
#8 24.98 │ exit code: 1
#8 24.98 ╰─> [6 lines of output]
#8 24.98     running develop
#8 24.98     /tmp/pip-build-env-ywijo3xu/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
#8 24.98       warnings.warn(
#8 24.98     /tmp/pip-build-env-ywijo3xu/overlay/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
#8 24.98       warnings.warn(
#8 24.98     error: [Errno 2] No such file or directory: 'unzip'
#8 24.98     [end of output]
#8 24.98
#8 24.98 note: This error originates from a subprocess, and is likely not a problem with pip.
------
executor failed running [/bin/sh -c cd /app &&     python -m venv --copies /app/.venv &&     . /app/.venv/bin/activate &&     pip install -e .]: exit code: 1
ERROR: Service 'covalent_data' failed to build : Build failed
```
