### ISSUE TITLE
Covalent Platforms

### ISSUE THREAD

**Issue by wjcunningham7** [AgnostiqHQ/covalent#451]
This epic is dedicated to expanding the list of platforms supported by Covalent. For an up-to-date list of supported platforms, refer to the [Compatibility Matrix](https://covalent.readthedocs.io/en/latest/getting_started/compatibility.html).

Priority Testing:
- [x] macOS 11 / Python 3.9
- [x] Ubuntu 20.04 / Python 3.10
- [x] Gentoo / Python 3.10

Untested:
- [x] macOS 11 / Python 3.10
- [x] CentOS 7 / Python 3.9
- [x] Fedora 35 / Python 3.8
- [ ] Alpine 3.14 / Python 3.8
- [ ] Raspbian Stretch / Python 3.8

If you use Covalent on a platform not officially supported, please give us feedback on your experience here!

**Comment by draentropia** [comment]
Ubuntu 22 / Python 3.10 user here. Doing "covalent start" I got this:
```
❯ covalent start
Traceback (most recent call last):
  File "/home/eortega/.local/bin/covalent", line 5, in <module>
    from covalent_dispatcher._cli.cli import cli
  File "/home/eortega/.local/lib/python3.10/site-packages/covalent_dispatcher/__init__.py", line 21, in <module>
    from .entry_point import cancel_running_dispatch, get_result, run_dispatcher
  File "/home/eortega/.local/lib/python3.10/site-packages/covalent_dispatcher/entry_point.py", line 31, in <module>
    from covalent._results_manager import Result
  File "/home/eortega/.local/lib/python3.10/site-packages/covalent/__init__.py", line 25, in <module>
    from . import executor
  File "/home/eortega/.local/lib/python3.10/site-packages/covalent/executor/__init__.py", line 35, in <module>
    from .base import BaseExecutor
  File "/home/eortega/.local/lib/python3.10/site-packages/covalent/executor/base.py", line 37, in <module>
    from .._workflow.transport import TransportableObject
  File "/home/eortega/.local/lib/python3.10/site-packages/covalent/_workflow/__init__.py", line 23, in <module>
    from .electron import electron
  File "/home/eortega/.local/lib/python3.10/site-packages/covalent/_workflow/electron.py", line 42, in <module>
    from .lattice import Lattice
  File "/home/eortega/.local/lib/python3.10/site-packages/covalent/_workflow/lattice.py", line 34, in <module>
    import covalent_ui.result_webhook as result_webhook
  File "/home/eortega/.local/lib/python3.10/site-packages/covalent_ui/result_webhook.py", line 25, in <module>
    import covalent_ui.app as ui_server
  File "/home/eortega/.local/lib/python3.10/site-packages/covalent_ui/app.py", line 34, in <module>
    from flask_socketio import SocketIO
  File "/home/eortega/.local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "/home/eortega/.local/lib/python3.10/site-packages/socketio/__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "/home/eortega/.local/lib/python3.10/site-packages/socketio/zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "/home/eortega/.local/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/home/eortega/.local/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/home/eortega/.local/lib/python3.10/site-packages/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/home/eortega/.local/lib/python3.10/site-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/home/eortega/.local/lib/python3.10/site-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/home/eortega/.local/lib/python3.10/site-packages/eventlet/greenio/base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/home/eortega/.local/lib/python3.10/site-packages/eventlet/timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
```
Still unclear if this only happens to me or it is a general issue.
