### ISSUE TITLE
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#914]
### Environment

- **Covalent version**: `0.110.2.post1`
- **Python version**: `3.10.5`
- **Operating system**: MacOS `12.4`

### What is happening?

Covalent fails on import.

### How can we reproduce the issue?

Attempt to import Covalent using Python 3.10.
```
~ $ python                                                                                                         (covalent)
Python 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:09:13) [Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import covalent as ct
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/covalent/__init__.py", line 25, in <module>
    from . import executor
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/covalent/executor/__init__.py", line 35, in <module>
    from .base import BaseExecutor
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/covalent/executor/base.py", line 37, in <module>
    from .._workflow.transport import TransportableObject
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/covalent/_workflow/__init__.py", line 23, in <module>
    from .electron import electron
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/covalent/_workflow/electron.py", line 42, in <module>
    from .lattice import Lattice
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/covalent/_workflow/lattice.py", line 34, in <module>
    import covalent_ui.result_webhook as result_webhook
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/covalent_ui/result_webhook.py", line 25, in <module>
    import covalent_ui.app as ui_server
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/covalent_ui/app.py", line 39, in <module>
    from flask_socketio import SocketIO
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/flask_socketio/__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/socketio/__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/socketio/zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/eventlet/greenio/base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/opt/anaconda3/envs/covalent/lib/python3.10/site-packages/eventlet/timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
```

### What should happen?

The Covalent package should be imported without error.

### Any suggestions?

I believe this is limited to Python 3.10. I tried to reproduce it on Python 3.9 and did not see the error.

**Comment by santoshkumarradha** [comment]
Seems like eventlet problem that has been solved. Reference - https://github.com/eventlet/eventlet/issues/733
