### ISSUE TITLE
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_signal_handlers' 

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#917]
### Environment

- **Covalent version**: `0.110.2.post1`
- **Python version**: 3.9
- **Operating system**: MacOS 12.4

### What is happening?

When dispatching workflows that involve loops in Python 3.9, the workflows fail. Logs show an asyncio error.
```
~ $ covalent logs                                                                                               (covalent-8)
Process DaskClusterProcess:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '8 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/site-packages/covalent_ui/app.py", line 68, in run
    cluster = LocalCluster()
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/site-packages/distributed/deploy/local.py", line 235, in __init__
    super().__init__(
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/site-packages/distributed/deploy/spec.py", line 251, in __init__
    super().__init__(
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/site-packages/distributed/deploy/cluster.py", line 64, in __init__
    self._loop_runner = LoopRunner(loop=loop, asynchronous=asynchronous)
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/site-packages/distributed/utils.py", line 399, in __init__
    self._loop = IOLoop()
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/site-packages/tornado/util.py", line 276, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 337, in initialize
    kwargs["asyncio_loop"] = loop = asyncio.new_event_loop()
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/asyncio/events.py", line 761, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/asyncio/selector_events.py", line 56, in __init__
    self._make_self_pipe()
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/asyncio/selector_events.py", line 107, in _make_self_pipe
    self._add_reader(self._ssock.fileno(), self._read_from_self)
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/asyncio/selector_events.py", line 258, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/selectors.py", line 523, in register
    self._selector.control([kev], 0, 0)
TypeError: changelist must be an iterable of select.kevent objects
Exception ignored in: <function BaseEventLoop.__del__ at 0x13b85b700>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/asyncio/base_events.py", line 688, in __del__
    self.close()
  File "/opt/anaconda3/envs/covalent-9/lib/python3.9/asyncio/unix_events.py", line 60, in close
    for sig in list(self._signal_handlers):
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_signal_handlers'
```

### How can we reproduce the issue?

1. Create a Conda environment with `python=3.9`
2. `pip install covalent`
3. `covalent start`
4. run this script
```
import covalent as ct


@ct.electron
def append(l, n):
    return l.append(n)


@ct.electron
@ct.lattice
def my_list(l, n):
    for i in range(0, n):
        l = append(l, i)
    return l


@ct.lattice
def get_len(l, s):
    l = my_list(l, len(s))
    length = 0
    for i in l:
        length = length + 1
    for i in s:
        length = length + 1
    return length


ct.dispatch(get_len)([0, 1], "hello")
```

### What should happen?

The workflow should be dispatched successfully and show green in the dashboard. Logs should show no errors.

### Any suggestions?

This appears to be limited to Python 3.9. The workflow successfully dispatches on Python 3.8.

**Comment by venkatBala** [comment]
On Linux (centos8), python=3.9, covalent version =0.110.2.post1 when running the posted example I get

![image](https://user-images.githubusercontent.com/15014089/181870318-fc5b492e-7f63-43f1-af8c-550ca7a316e8.png)

I got it to work by modifying the `append` electron as follows

```python
@ct.electron
def append(l, n):
    l.append(n)
    return l
````

**Comment by scottwn** [comment]
@santoshkumarradha is this acceptable ux?

**Comment by cjao** [comment]
```python
@ct.electron
def append(l, n):
    l.append(n)
    return l
```
This would cause a sequence of append operations to have O(n^2) complexity because each `append()` electron would make a deep copy of the list.

**Comment by cjao** [comment]
@venkatBala we need to figure out the cause of your error. Is append being invoked on `NoneType` because `l` wasn't computed correctly?

@scottwn do you still see the error with [the line](https://github.com/AgnostiqHQ/covalent/blob/a1a87708eaa4da01dd4cc799e0014b1b98e9b61f/covalent_dispatcher/_core/execution.py#L813) `uvloop.install()` commented out and after `pip uninstall uvloop`? This would switch asyncio from uvloop back to the built-in event loop implementation.

**Comment by cjao** [comment]
Reproducer:

```python
import asyncio
import uvloop

async def show_signal_handlers():
    loop = asyncio.get_running_loop()
    print(type(loop))
    print(loop._signal_handlers)

asyncio.run(show_signal_handlers())

print("\nReplacing built-in event loop with uvloop\n")
uvloop.install()

asyncio.run(show_signal_handlers())
```
Output:
```
<class 'asyncio.unix_events._UnixSelectorEventLoop'>
{}

Replacing built-in event loop with uvloop

<class 'uvloop.Loop'>
Traceback (most recent call last):
  File "917_reproducer.py", line 15, in <module>
    asyncio.run(show_signal_handlers())
  File "/var/home/casey/.conda/envs/covaenv/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "917_reproducer.py", line 8, in show_signal_handlers
    print(loop._signal_handlers)
AttributeError: 'Loop' object has no attribute '_signal_handlers'
```
[Uvloop implements the public event loop API](https://uvloop.readthedocs.io/) but didn't fully remove all references to the built-in event loop's internals.

**Comment by cjao** [comment]
@kessler-frost in view of this, would it be alright to switch back to the built-in event loop for now?
