### ISSUE TITLE
`covalent_migrations` path doesn't exist

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#967]
### Environment

- **Covalent version**: `Version: 0.161.1rc0`
- **Python version**: `Python 3.8.13`
- **Operating system**: MacOS `12.5`

### What is happening?

After installing a Covalent prerelease, `covalent start` fails with a `Path doesn't exist` error.

### How can we reproduce the issue?

1. Install the Covalent prerelease, `pip install covalent --pre`
2. From an executor root directory (or presumably an arbitrary directory?), `covalent purge` then `covalent start`.
3. `covalent db migrate` will give the same `Path doesn't exist` error as `covalent start`.

```
~/covalent-braket-plugin (develop|✔) [1]$ covalent status                                                      (covalent-pre)
__init__.py: Line 135 in _populate_executor_map_from_module:
WARNING - covalent_braket_plugin.braket does not seem to have a well-defined plugin class.
Specify the plugin class with 'executor_plugin_name = <plugin class name>' in the covalent_braket_plugin.braket module.
Covalent server is running at http://localhost:48008.
~/covalent-braket-plugin (develop|✔) $ covalent purge                                                          (covalent-pre)
__init__.py: Line 135 in _populate_executor_map_from_module:
WARNING - covalent_braket_plugin.braket does not seem to have a well-defined plugin class.
Specify the plugin class with 'executor_plugin_name = <plugin class name>' in the covalent_braket_plugin.braket module.
Covalent server has stopped.
Covalent server files have been purged.
~/covalent-braket-plugin (develop|✔) $ covalent start                                                          (covalent-pre)
__init__.py: Line 135 in _populate_executor_map_from_module:
WARNING - covalent_braket_plugin.braket does not seem to have a well-defined plugin class.
Specify the plugin class with 'executor_plugin_name = <plugin class name>' in the covalent_braket_plugin.braket module.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/covalent-pre/bin/covalent", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/covalent-pre/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/covalent-pre/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/covalent-pre/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/covalent-pre/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/covalent-pre/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/covalent-pre/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/anaconda3/envs/covalent-pre/lib/python3.8/site-packages/covalent_dispatcher/_cli/service.py", line 318, in start
    if db.is_migration_pending and not ignore_migrations:
  File "/opt/anaconda3/envs/covalent-pre/lib/python3.8/site-packages/covalent/_data_store/datastore.py", line 93, in is_migration_pending
    return self.current_head() != self.current_revision()
  File "/opt/anaconda3/envs/covalent-pre/lib/python3.8/site-packages/covalent/_data_store/datastore.py", line 87, in current_head
    script = ScriptDirectory.from_config(alembic_config)
  File "/opt/anaconda3/envs/covalent-pre/lib/python3.8/site-packages/alembic/script/base.py", line 210, in from_config
    return ScriptDirectory(
  File "/opt/anaconda3/envs/covalent-pre/lib/python3.8/site-packages/alembic/script/base.py", line 95, in __init__
    raise util.CommandError(
alembic.util.exc.CommandError: Path doesn't exist: '/Users/scott/covalent-braket-plugin/covalent_migrations'.  Please use the 'init' command to create a new scripts folder.
~/covalent-braket-plugin (develop|✔) [1]$ covalent db init                                                     (covalent-pre)
__init__.py: Line 135 in _populate_executor_map_from_module:
WARNING - covalent_braket_plugin.braket does not seem to have a well-defined plugin class.
Specify the plugin class with 'executor_plugin_name = <plugin class name>' in the covalent_braket_plugin.braket module.
Usage: covalent db [OPTIONS] COMMAND [ARGS]...
Try 'covalent db --help' for help.

Error: No such command 'init'.
~/covalent-braket-plugin (develop|✔) [2]$ covalent db migrate                                                  (covalent-pre)
__init__.py: Line 135 in _populate_executor_map_from_module:
WARNING - covalent_braket_plugin.braket does not seem to have a well-defined plugin class.
Specify the plugin class with 'executor_plugin_name = <plugin class name>' in the covalent_braket_plugin.braket module.
Path doesn't exist: '/Users/scott/covalent-braket-plugin/covalent_migrations'.  Please use the 'init' command to create a new scripts folder.
There was an issue running migrations.
Please read https://covalent.readthedocs.io/en/latest/how_to/db/migration_error.html for more information.
```

### What should happen?

Covalent should start successfully or gracefully prompt the user to `covalent db migrate`. Migration should run successfully.

**Comment by AlejandroEsquivel** [comment]
Should be closed when https://github.com/AgnostiqHQ/covalent/pull/968 is merged
